### ISSUE TITLE
use_waiter() on single output?

### ISSUE THREAD

**Issue by hadley** [JohnCoene/waiter#18]
I think it would be useful if you could use waiter on a single output (or generally any div) — that would give you something like butler, but a little more visually prominent, and with a spinner instead of a progress bar that slows down exponentially.

**Comment by JohnCoene** [comment]
I reckon I have managed to tackle this issue: added an `id` (must be an id does not take other selectors, e.g.: class) argument to `show_waiter`, if the latter is `NULL` the full screen waiter is used, if it is passed then the waiter is shown as overlay over the div/plot with said `id`.

It also gave an idea, perhaps a bad one, to add an argument to hide the waiter when the plot is drawn (when the JavaScript `shiny:value` event is fired essentially). This is enabled by setting the new argument `hide_on_drawn` to `TRUE` (defaults to `FALSE`).

One can still display a loading bar by using the hostess (_not_ exponentially growing).

```r
library(shiny)
library(waiter)

ui <- fluidPage(
	h1("waiter"),
	use_waiter(),
	use_hostess(),
	actionButton("draw", "redraw"),
	fluidRow(
		column(4, h3("Loading bar (hostess)"), plotOutput("plot1")),
		column(4, h3("Spinner"), plotOutput("plot2")),
		column(4, h3("Hide on drawn"), plotOutput("plot3"))
	)
)

server <- function(input, output) {

	dataset <- reactive({
		input$draw
		rnorm(100)
	})

	observeEvent(input$draw, {

		# show with loading bar (hostess)
		show_waiter(
			hostess_loader("myHostess"),
			id = "plot1", # specify id of plot to overlay
			color = "white"
		)

		# show with spinner
		show_waiter(
			spin_3(),
			id = "plot2"
		)

		# show with spinner AND hide_on_drawn
		show_waiter(
			spin_3(),
			id = "plot3",
			color = "grey",
			hide_on_drawn = TRUE
		)

		# increment progress bar
		hostess <- Hostess$new("myHostess")
		for(i in 1:10){
			Sys.sleep(runif(1)) 
			hostess$set(i * 10)
		}

		# hide waiters
		hide_waiter(id = "plot1")
		hide_waiter(id = "plot2")

	})

	output$plot1 <- renderPlot(plot(hist(dataset())))
	output$plot2 <- renderPlot(plot(dataset(), type = "l"))
	output$plot3 <- renderPlot(plot(dataset()))

}

shinyApp(ui, server)
```

![waiter-overlay](https://user-images.githubusercontent.com/7833796/70523815-1575f700-1b44-11ea-9746-abd530db256b.gif)

Looking forward to what you think, may be closed if solved.

**Comment by hadley** [comment]
I rewrote it a little (rewriting stuff is how I understand 😄) — having a separate `reactive()` and `observeEvent()` caused an unnecessary redraw (which you can see in the at the end of your gif). I really like the `hide_on_plot` argument, although I worry it's very specific to plots, and it would be nicer if it could work with any output (while accepting that might be a lot of extra work that isn't worth it)

```R
library(shiny)
library(waiter)

ui <- fluidPage(
	use_waiter(),
	use_hostess(),
	fluidRow(
		column(4, h3("Loading bar (hostess)"), plotOutput("plot1")),
		column(4, h3("Spinner"), plotOutput("plot2")),
		column(4, h3("Hide on drawn"), plotOutput("plot3"))
	),
	actionButton("draw", "redraw")
)

server <- function(input, output) {
	dataset <- reactive({
	  input$draw
  
		show_waiter(hostess_loader("myHostess"), id = "plot1", color = "white")
		show_waiter(spin_3(), id = "plot2")
		show_waiter(spin_3(), id = "plot3", color = "grey", hide_on_drawn = TRUE)

		# increment progress bar
		hostess <- Hostess$new("myHostess")
		for(i in 1:10){
			Sys.sleep(0.1) 
			hostess$set(i * 10)
		}

		# hide waiters
		hide_waiter("plot1")
		hide_waiter("plot2")
		
		rnorm(100)
	})

	output$plot1 <- renderPlot(plot(dataset()))
	output$plot2 <- renderPlot(plot(dataset()))
	output$plot3 <- renderPlot(plot(dataset()))
}

shinyApp(ui, server)
```

Rewriting the code made me realised that I think `waiter_` should be the prefix, rather than the suffix: that makes autocomplete more useful because I think typically you'll remember that you want to use waiter, but don't remember the exact method name you want:

```R
waiter_show("plot1", hostess_loader("myHostess"), color = "white")
waiter_show("plot2", spin_3())
waiter_show("plot3", spin_3(), color = "grey", hide_on_drawn = TRUE)
```

I'd also suggest making `id` the first argument (defaulting it to `NULL`) so that showing and hiding is more symmetric:

```R
waiter_hide("plot1")
waiter_hide("plot2")
```

(It's currently not clear what the default `html = ""` argument does; you might want to make it `NULL` or set it a spinner by default)

I also wonder if you could provide a Hostess method that returned a loader. Then you could do:

```R
hostess <- Hostess$new()
waiter_show("plot1", hostess$loader(), color = "white")

for(i in 1:10){
	Sys.sleep(0.1) 
	hostess$set(i * 10)
}
```

(Here I'm imaging that `Hostess$new()` would default to a randomly selected id)

(

**Comment by JohnCoene** [comment]
OK, all around great suggestions again, slightly annoyed it did not come to my mind before if I may be honest :)

- [x] Deprecated now "old" functions in favour of `waiter_` prefixed functions.
- [x] the `id` argument is first in "new" `waiter_` prefixed functions
- [x] `html` argument defaults to `spin_1` except for `update` where it defaults to `NULL`
- [x] Added a method to `Hostess` to generate the loader.

I love the last of the above, because it's now in the method, there is no need to specify an `id` (defaults to `NULL` might be nice to some to customize CSS), it's all handled within the R6 class.

Your re-written app with new function names and functionalities below.

```r
library(shiny)
library(waiter)

ui <- fluidPage(
  use_waiter(),
  use_hostess(),
  fluidRow(
    column(4, h3("Loading bar (hostess)"), plotOutput("plot1")),
    column(4, h3("Spinner"), plotOutput("plot2")),
    column(4, h3("Hide on drawn"), plotOutput("plot3"))
  ),
  actionButton("draw", "redraw")
)

server <- function(input, output) {
  dataset <- reactive({
    input$draw

    # create hostess _without_ id
    hostess <- Hostess$new()

    waiter_show("plot1", hostess$loader(text_color = "black"), color = "white")
    waiter_show("plot2", spin_3())
    waiter_show("plot3", spin_3(), color = "grey", hide_on_drawn = TRUE)

    # increment progress bar
    for (i in 1:10) {
      Sys.sleep(0.1)
      hostess$set(i * 10)
    }

    # hide waiters
    waiter_hide("plot1")
    waiter_hide("plot2")

    rnorm(100)
  })

  output$plot1 <- renderPlot(plot(dataset()))
  output$plot2 <- renderPlot(plot(dataset()))
  output$plot3 <- renderPlot(plot(dataset()))
}

shinyApp(ui, server)
```

Perhaps some clarification on the `hide_on_drawn` argument (which hints at the fact the argument is probably not aptly named). It will work on any `uiOutput`, htmlwidget, tableOutput/DT, etc.

```r
library(shiny)
library(waiter)

ui <- fluidPage(
  use_waiter(),
  use_hostess(),
  actionButton("draw", "Generate"),
  uiOutput("someUI")
)

server <- function(input, output) {
  content <- reactive({
    input$draw

    waiter_show("someUI", hide_on_drawn = TRUE)

    Sys.sleep(3)

    div(
      style = "height:300px;",
      h1("Hello")
    )
  })

  output$someUI <- renderUI({
    content()
  })
}

shinyApp(ui, server)
```
![waiter-hello](https://user-images.githubusercontent.com/7833796/70560407-cdc58e80-1b88-11ea-8123-fa225b426641.gif)

I'm not great at naming things, so all for renaming `hide_on_drawn` argument, suggestions are more than welcome?

**Comment by hadley** [comment]
Looks great!

Maybe call it `hide_on_render`? Or even `auto_hide`? Maybe it's useful enough it should be the default when `!is.null(id)`?  Or maybe it should be a separate function like `waiter_auto()`?

**Comment by JohnCoene** [comment]
Changes pertaining to this issue since last comment.

On the issue of the `hide_on_drawn` argument, I went with renaming it to `hide_on_render` thinking `auto_hide` would lead the the question "auto, how exactly?."

The now named `hide_on_render` argument also watches for `shiny:recalculated` event which leads to smoother transition; the previous plot used to flash after waiter was hidden (see previous gif), this no longer should occur.

```r
library(shiny)
library(waiter)

ui <- fluidPage(
  use_waiter(),
  actionButton("draw", "draw"),
  plotOutput("plot")
)

server <- function(input, output) {
  dataset <- reactive({
    input$draw

    Waiter$new("plot", hide_on_render = TRUE)$
      show()

    Sys.sleep(5)

    runif(100)
  })

  output$plot <- renderPlot(plot(dataset()))
}

shinyApp(ui, server)
```

![waiter-recalc](https://user-images.githubusercontent.com/7833796/70660389-5c5a0e80-1c62-11ea-9549-d4a473cc75db.gif)

If we have `hide_on_render` in waiter we ought to have it in the waitress too.

```r
library(shiny)
devtools::load_all()

ui <- fluidPage(
  use_waitress(),
  actionButton("draw", "draw"),
  plotOutput("plot")
)

server <- function(input, output) {
  dataset <- reactive({
    input$draw

    waitress <- Waitress$
      new("#plot", hide_on_render = TRUE, infinite = TRUE)$
      start(h3("Loading..."), background_color = "white")

    Sys.sleep(5)

    runif(100)
  })

  output$plot <- renderPlot(plot(dataset()))
}

shinyApp(ui, server)
```

![waitress-recalc](https://user-images.githubusercontent.com/7833796/70660542-bc50b500-1c62-11ea-91e0-96b66c3fd77e.gif)

I think I can close this issue now unless there is something else I might have missed or any other suggestion.

**Comment by hadley** [comment]
That looks awesome!

**Comment by JohnCoene** [comment]
Added the ability to pass multiple ids as vector or list to the waiter. It's useful as I find myself often having to duplicate waiters because I need them to overlay different elements.

```r
library(shiny)
library(waiter)

ui <- fluidPage(
  use_waiter(),
  actionButton("btn", "Render"),
  fluidRow(
    column(6, plotOutput("plot1")),
    column(6, plotOutput("plot2"))
  )
)

server <- function(input, output) {

  w <- Waiter$new(c("plot1", "plot2"))

  dataset <- reactive({
    input$btn
    w$show()
    Sys.sleep(2)
    runif(100)
  })

  output$plot1 <- renderPlot(plot(dataset()))
  output$plot2 <- renderPlot(plot(dataset()))

}

shinyApp(ui, server)
```

![waiter-multi](https://user-images.githubusercontent.com/7833796/71556627-56727480-2a3b-11ea-8c96-79b02902c657.gif)

One can, for better or worse, specify different spinners/content for the waiters by passing a list (the same length as ids) to `html`.

```r
library(shiny)
library(waiter)

ui <- fluidPage(
  use_waiter(),
  actionButton("btn", "Render"),
  fluidRow(
    column(6, plotOutput("plot1")),
    column(6, plotOutput("plot2"))
  )
)

server <- function(input, output) {

  w <- Waiter$new(
    list("plot1", "plot2"),
    html = list(spin_1(), spin_2())
  )

  dataset <- reactive({
    input$btn
    w$show()
    Sys.sleep(2)
    runif(100)
  })

  output$plot1 <- renderPlot(plot(dataset()))
  output$plot2 <- renderPlot(plot(dataset()))

}

shinyApp(ui, server)
```

![waiter-multi2](https://user-images.githubusercontent.com/7833796/71556629-5a9e9200-2a3b-11ea-90d1-b291083230e5.gif)

**Comment by hadley** [comment]
Given that ids will always be strings, I think that the `id` parameter should only take a character vectors (not lists)

**Comment by JohnCoene** [comment]
I'm gonna go ahead and close this as I think the issue has been tackled and I am prepping waiter for a CRAN release, feel free to re-open if it's not the case. Thanks again.

**Comment by hadley** [comment]
Thanks for all your work on this!! 🎉

**Comment by JohnCoene** [comment]
Thank you for all the great advice and inputs! Please feel free to share any other thoughts (or issue) on the package it's always welcome. This version (`0.1.0`) is "is on its way to CRAN."
