### ISSUE TITLE
Document Butler and Waiter R6 classes separately

### ISSUE THREAD

**Issue by hadley** [JohnCoene/waiter#19]
Currently you see the methods for the internal classes on the same page as the user facing functions. I think that's a bit confusing since most users shouldn't need the R6 classes (if I understand the standard operation of the package correctly).

**Comment by JohnCoene** [comment]
Indeed this must be have been confusing to many; documentation is now split. Using the R6 classes are indeed not essential I personally thought it'd be convenient as otherwise one has to type and re-type certain arguments, namely the `id` of the element over which the waiter/progress bar is shown.

e.g.: 

```r
host <- hostess$new(id = "myId")
host$set(10)
host$set(90)
```

vs.

```r
hostess_init("myId")
hostess_set("myId", 10)
hostess_set("myId", 90)
```

R6 seems "better" but I feel many users are uncomfortable with it so I provide both: perhaps this is the mistake and I should restrict to one way of using it?

**Comment by hadley** [comment]
Yeah, I think you should provide only one way, and my sense would be to go with R6 since it's lower duplication.

**Comment by hadley** [comment]
And I think most people are either already comfortable with R6, or can quickly become comfortable with it. At least in my experience, people pick up the usage of R6 pretty quickly.

**Comment by JohnCoene** [comment]
Deprecated many functions in favour of R6 classes, only kept `waiter_show` and `waiter_hide`

**Comment by JohnCoene** [comment]
I'm going to go ahead and close I this as I think this has been addressed, feel free to reopen.
