### ISSUE TITLE
Connection between butler and waitress?

### ISSUE THREAD

**Issue by hadley** [JohnCoene/waiter#20]
It seems like butler is just a special case of waitress with a progress bar that updates exponentially. Could this just be an argument to waitress?

**Comment by JohnCoene** [comment]
`butler` is a product of a combination of oversight and laziness on my part. Butler relies on a different 
JavaScript library to create the loading bar. It's lazy because it can be done with the `waitress`.

I've just added a new argument `infinite` to the `Waitress` initialisation.

```r
library(shiny)
library(waiter)

ui <- fluidPage(
  use_waitress(),
  plotOutput("plot", width = 400)
)

server <- function(input, output){

  waitress <- Waitress$new("#plot", theme = "overlay", infinite = TRUE) # call the waitress
  waitress$start()

  output$plot <- renderPlot({
    Sys.sleep(3)
    hist(runif(100))
    waitress$close() 
  })

}

shinyApp(ui, server)
```

This could probably work, getting rid of butler entirely I would suggest. Though it admittedly would need a more interesting easing function applied on the progress bar.

**Comment by JohnCoene** [comment]
Going ahead and closing this as I believe it has been tackled, feel free to reopen.

**Comment by AB-Kent** [comment]
`waitress` does not seem to be a full replacement for `butler`. AFAICKT `waitress` does not support multiple colors or configurable width, and it does eventually reach the end. In particular, what is the `waitress` equivalent of this?
```
library(shiny)
library(waiter)

ui <- fluidPage(
  use_butler()
)

server <- function(input, output){
  config_butler(thickness = 10,
                colors = list("0" = "#ff0055", "1" = "#6A0FBA"))
  show_butler()
}

shinyApp(ui, server)
```
