### ISSUE TITLE
Static message with selector

### ISSUE THREAD

**Issue by hadley** [JohnCoene/waiter#21]
I think it would be a useful complement to waitress to overlay a static message on an element of your choosing.

**Comment by hadley** [comment]
In other words, waiter is currently great for displaying progress bars, but I think with only a small amount of work, you could also allow it to display notifications.

**Comment by JohnCoene** [comment]
So I have added the ability to display content in the wiatress (any htmltools::tag).

```r
library(shiny)
library(waiter)

ui <- fluidPage(
	use_waitress(),
	actionButton("draw", "redraw"),
  plotOutput("plot")
)

server <- function(input, output) {

  dataset <- reactive({
    input$draw
    
    w <- Waitress$
      new()$
      start(h3("LOADING"), background_color = "white")

    purrr::map(1:10, function(x) {
      Sys.sleep(.3)
      w$inc(x * 10)
    })

    w$close()

    runif(100)
  })

  output$plot <- renderPlot(plot(dataset()))

}

shinyApp(ui, server)

```

![waitress-msg](https://user-images.githubusercontent.com/7833796/70852686-afbb9f00-1ea4-11ea-9a61-cf80c7030324.gif)

I also added the ability to show notifications. It looks very much similart to the code above, instead of `start` we `notify`.

```r
library(shiny)
library(waiter)

ui <- fluidPage(
	use_waitress(),
	actionButton("draw", "redraw"),
  plotOutput("plot")
)

server <- function(input, output) {

  dataset <- reactive({
    input$draw
    
    w <- Waitress$
      new()$
      notify(h3("LOADING"))

    purrr::map(1:10, function(x) {
      Sys.sleep(.3)
      w$inc(x * 10)
    })

    w$close()

    runif(100)
  })

  output$plot <- renderPlot(plot(dataset()))

}

shinyApp(ui, server)
```

![waitress-notif1](https://user-images.githubusercontent.com/7833796/70852755-8a7b6080-1ea5-11ea-87b9-8a7f0490f53c.gif)

There are a few arguments to the `notify` method, e.g.: `position`. One can show more than one notification at once, they _should_ stack up/down correctly. When specifying a `selector` and `hide_on_render` with the `notify` method, the waitress is not layered on top of said selector but nonetheless hides when it has rendered.

```r
library(shiny)
library(waiter)

ui <- fluidPage(
	use_waitress(),
	actionButton("draw", "redraw"),
  plotOutput("plot")
)

server <- function(input, output) {

  dataset <- reactive({
    input$draw
    
    Waitress$
      new("#plot", infinite = TRUE, hide_on_render = TRUE)$
      notify(h3("LOADING 1"), position = "tr")

    Sys.sleep(2)

    Waitress$
      new("#plot", infinite = TRUE, hide_on_render = TRUE)$
      notify(h3("LOADING 2"), position = "tr")

    Sys.sleep(2)

    runif(100)
  })

  output$plot <- renderPlot(plot(dataset()))

}

shinyApp(ui, server)
```

![waitress-notif2](https://user-images.githubusercontent.com/7833796/70852910-49844b80-1ea7-11ea-9f7d-4d023898bf72.gif)

Then again it allows for silly things.

```r
library(shiny)
library(waiter)

gif <- paste0("https://media1.tenor.com/images/cb27704982766b4f02691ea975d9a259/",
  "tenor.gif?itemid=11365139")

ui <- fluidPage(
	use_waitress(),
	actionButton("draw", "redraw", icon = icon("send")),
  plotOutput("plot")
)

server <- function(input, output) {

  notif <- tagList(
    h4(icon("keyboard-o"), "Typing"),
    tags$img(src = gif, height = 200)
  )

  dataset <- reactive({
    input$draw
    
    Waitress$
      new("#plot", infinite = TRUE, hide_on_render = TRUE)$
      notify(notif, position = "tr")

    Sys.sleep(3)

    runif(100)
  })

  output$plot <- renderPlot(plot(dataset()))

}

shinyApp(ui, server)
```

![waitress-typing](https://user-images.githubusercontent.com/7833796/70853071-628dfc00-1ea9-11ea-930b-495f318fd197.gif)

Without going overbaord.

```r
library(shiny)
library(waiter)

ui <- fluidPage(
	use_waitress(),
	actionButton("draw", "redraw", icon = icon("send")),
  plotOutput("plot")
)

server <- function(input, output) {

  dataset <- reactive({
    input$draw
    
    Waitress$
      new(
        "#plot", 
        infinite = TRUE, 
        hide_on_render = TRUE, 
        theme = "overlay-percent"
      )$
      notify()

    Sys.sleep(3)

    runif(100)
  })

  output$plot <- renderPlot(plot(dataset()))

}

shinyApp(ui, server)
```

![waitress-simple](https://user-images.githubusercontent.com/7833796/70853130-25763980-1eaa-11ea-9768-d6f900a83918.gif)

**Comment by JohnCoene** [comment]
Issue with notifications on mobile #27

**Comment by JohnCoene** [comment]
Thanks Hadley, all sorted I reckon. Feel free to re-open if I missed something.
