### ISSUE TITLE
Unexpected behavior with waiter spinner with shinydashboard

### ISSUE THREAD

**Issue by tyluRp** [JohnCoene/waiter#43]
Hi @JohnCoene !

I am trying to add a loading screen to a datatable that is inside a shinydashboard box. However, the spinner looks like a really small box rather than the actual spinner. This seems to go away if I manually assign a spinner. A reproducible example below:

```r
library(shiny)
library(shinydashboard)
library(waiter)

ui <- dashboardPage(
  dashboardHeader(),
  dashboardSidebar(),
  dashboardBody(
    use_waiter(),
    actionButton("draw", "draw plot"),
    box(plotOutput("plot"))
  )
)

server <- function(input, output) {
  w <- Waiter$new(id = "plot")
  # w <- Waiter$new(id = "plot", html = spin_half())
  
  dataset <- reactive({
    input$draw
    w$show()
    Sys.sleep(3)
    w$hide()
    
    runif(100)
  })
  
  output$plot <- renderPlot(plot(dataset()))
}

shinyApp(ui, server)
```

**Comment by JohnCoene** [comment]
Hi Tyler, thank you for reporting this!

Indeed one of the CSS classes clashed with shinydashboard and thus instead of showing the spinner was showing the box just like `box()` funnily enough. I pushed a fix, you can reinstall the package from Github and it should work.

```r
# install.packages("remotes")
remotes::install_github("JohnCoene/waiter")
```

Note that if the `id` passed is that of a rendered element, like a plot, a table, a renderUI, then waiter automatically hides the loading screen when it is re-rendered, see the ["partial" doc entry](https://waiter.john-coene.com/#/waiter?id=partial).

```r
library(shiny)
library(shinydashboard)
library(waiter)

ui <- dashboardPage(
  dashboardHeader(),
  dashboardSidebar(),
  dashboardBody(
    use_waiter(),
    actionButton("draw", "draw plot"),
    box(plotOutput("plot"))
  )
)

server <- function(input, output) {
  w <- Waiter$new(id = "plot")
  
  dataset <- reactive({
    input$draw
    w$show()
    Sys.sleep(3)

    # hides automatically 
    #w$hide()
    
    runif(100)
  })
  
  output$plot <- renderPlot(plot(dataset()))
}

shinyApp(ui, server)
```

Let me know if this works so I can close the issue. Thanks again!

**Comment by tyluRp** [comment]
Working on my end, thanks! 👍
