### ISSUE TITLE
Option to centre spinner and logo

### ISSUE THREAD

**Issue by MaxKerney** [JohnCoene/waiter#57]
Thanks for the great package! Currently, when using a spinner and a logo the spinner is positioned under the logo, but would it be possible to have the spinner and logo aligned in the centre of the page, such that the spinner revolves around the logo? Using `spin_loaders(3)` I've tried modifying the css through the style argument, but have only been able to modify the height and width of the spinner to make it large enough to fit around a logo; I haven't been able to align them in the centre of the page, at least not in a way that's robust to changes of screen size. I've also tried wrapping `spin_loaders()` in `div()` and altering the css positioning of that, but with no luck. Apologies if I'm just missing something basic! Thanks.

**Comment by JohnCoene** [comment]
Hi Max,

Thanks you.

The `logo` argument is actually somewhat irrelevant since you can pass any HTML and are not limited to just passing the spinner.

The spinners are just convenience functions to generate HTML tags and attributes, you can retrieve those with `as.character`, e.g.: `cat(as.character(waiter::spin_loaders(3)))`.

With this you can build a custom spinner (`custom_spin` below). It might require you to fiddle with the CSS a bit in order to ensure the image and spinner do stack.


```r
library(shiny)
library(waiter)

# print the HTML
cat(as.character(waiter::spin_loaders(3)))

custom_spin <- function(){
  tagList(
    img(src = "https://www.r-project.org/Rlogo.png", style="position:absolute;margin:auto;"),
    div(class = "loaderz-03", style="width:13em;height:13em;")
  )
}

ui <- fluidPage(
  use_waiter(), # include dependencies
  actionButton("show", "Show loading for 5 seconds")
)

server <- function(input, output, session){
  # create a waiter
  w <- Waiter$new(html = custom_spin())

  # on button click
  observeEvent(input$show, {
    w$show()
    Sys.sleep(5)
    w$hide()
  })
}

shinyApp(ui, server)
```

Let me know if this helps

**Comment by MaxKerney** [comment]
Thanks for replying so quickly, and that's really helpful - I've been able to achieve exactly what I wanted. Thank you!
