### ISSUE TITLE
logging events

### ISSUE THREAD

**Issue by fmmattioni** [JohnCoene/waiter#83]
Hey @JohnCoene!

While debugging an app using the latest version of {waiter}, I have noticed that `waiter.js` has been logging the shiny events to the console:

https://github.com/JohnCoene/waiter/blob/003795d1610e525371ff81b0996b2089522f033b/inst/assets/waiter/waiter.js#L184-L190

Just wondering if this is intended?

**Comment by JohnCoene** [comment]
Thanks! I removed it.

**Comment by trafficonese** [comment]
Here is another one. ;)

https://github.com/JohnCoene/waiter/blob/477789d177556f9fd11c9120f5b71b72015706c1/R/waiter.R#L235

The app also always starts with this message:
`waiter_show_on_load - shiny not connected yet: Shiny.setInputValue is not a function`

**Comment by JohnCoene** [comment]
Thanks, I removed the `console.log('idle')`

I placed the second message on purpose; it's good to know I think because we need `waiter_show_on_load` to run _before_ shiny connects in order to avoid having app content flash before the loading screen shows. Therefore with that function the event cannot be send to the server (shiny is not connected yet) but there's no real way to communicate that to the user other than with a console message (to the best of my knowledge).

https://github.com/JohnCoene/waiter/blob/322df5315c9e40579a07df72c3ebad6a61f2f738/inst/assets/waiter/waiter.js#L121
